shopban/Models/Giohang.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace shopban.Models
{
    public class Giohang
    {
        ShopDataDataContext data = new ShopDataDataContext();
        public int iMaSp { set; get; }
        public string sTenSp { set; get; }
        public string sAnhbia { set; get; }
        public Double dDongia { set; get; }
        public int iSoluong { set; get; }
        public Double dThanhtien
        {
            get { return iSoluong * dDongia; }

        }
        public Giohang(int MaSp)
        {
            iMaSp = MaSp;
            SANPHAM sp = data.SANPHAMs.Single(n => n.MaSP == iMaSp);
            sTenSp = sp.TenSP;
            sAnhbia = sp.Anhbia;
            dDongia = double.Parse(sp.Giaban.ToString());
            iSoluong = 1;
        }
    }
}

shopban/Controllers/GiohangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shopban.Models;
namespace shopban.Controllers
{
    public class GiohangController : Controller
    {
        ShopDataDataContext data = new ShopDataDataContext();
        // GET: Giohang
        public PartialViewResult Index()
        {
            List<Giohang> lstGiohang = Laygiohang();
            //if (lstGiohang.Count == 0)
            //{
            //    return PartialView();
            //}
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            return PartialView(lstGiohang);
       
        }
        public PartialViewResult Gia()
        {
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            return PartialView();
        }
        
        public List<Giohang> Laygiohang()
        {
            List<Giohang> lstGiohang = Session["Giohang"] as List<Giohang>;
            if (lstGiohang == null)
            {
                lstGiohang = new List<Giohang>();
                Session["Giohang"] = lstGiohang;
            }
            return lstGiohang;
        }

        public ActionResult ThemGiohang(int iMaSp, string strURL)
        {

            List<Giohang> lstGiohang = Laygiohang();

            Giohang sanpham = lstGiohang.Find(n => n.iMaSp == iMaSp);
            if (sanpham == null)
            {
                sanpham = new Giohang(iMaSp);
                lstGiohang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoluong++;
                return Redirect(strURL);
            }
        }

        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<Giohang> lstGiohang = Session["GioHang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                iTongSoLuong = lstGiohang.Sum(n => n.iSoluong);
            }
            return iTongSoLuong;
        }
        private double TongTien()
        {
            double iTongTien = 0;
            List<Giohang> lstGiohang = Session["GioHang"] as List<Giohang>;
            if (lstGiohang != null)
            {
                iTongTien = lstGiohang.Sum(n => n.dThanhtien);
            }
            return iTongTien;
        }
        public ActionResult GioHang()
        {
            List<Giohang> lstGiohang = Laygiohang();
            if (lstGiohang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            return View(lstGiohang);
        }
        public ActionResult GiohangPartial()
        {
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();
            return PartialView();
        }
        public ActionResult CapnhatGiohang(int iMaSP, FormCollection f)
        {

            //Lay gio hang tu Session
            List<Giohang> lstGiohang = Laygiohang();
            //Kiem tra sach da co trong Session["Giohang"]
            Giohang sanpham = lstGiohang.SingleOrDefault(n => n.iMaSp == iMaSP);
            //Neu ton tai thi cho sua Soluong
            if (sanpham != null)
            {
                sanpham.iSoluong = int.Parse(f["txtSoluong"].ToString());
            }
            return RedirectToAction("Giohang");
        }
        public ActionResult XoaGiohang(int iMaSP)
        {
            //Lay gio hang tu Session
            List<Giohang> lstGiohang = Laygiohang();
            //Kiem tra sach da co trong Session["Giohang"]
            Giohang sanpham = lstGiohang.SingleOrDefault(n => n.iMaSp == iMaSP);
            //Neu ton tai thi cho sua Soluong
            if (sanpham != null)
            {
                lstGiohang.RemoveAll(n => n.iMaSp == iMaSP);
                return RedirectToAction("GioHang");

            }
            if (lstGiohang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");
        }
        public ActionResult XoaTatcaGiohang()
        {
            //Lay gio hang tu Session
            List<Giohang> lstGiohang = Laygiohang();
            lstGiohang.Clear();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult DatHang()
        {
            //Kiem tra dang nhap
            if (Session["Taikhoan"] == null || Session["Taikhoan"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "Nguoidung");
            }
            if (Session["Giohang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            //Lay gio hang tu Session
            List<Giohang> lstGiohang = Laygiohang();
            if (lstGiohang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.Tongsoluong = TongSoLuong();
            ViewBag.Tongtien = TongTien();

            return View(lstGiohang);
        }
        [HttpPost]
        public ActionResult DatHang(FormCollection collection)
        {
            //Them Don hang
            DONDATHANG ddh = new DONDATHANG();
            KHACHHANG kh = (KHACHHANG)Session["Taikhoan"];
            List<Giohang> gh = Laygiohang();
            ddh.MaKH = kh.MaKH;
            ddh.Ngaydat = DateTime.Now;
            var ngaygiao = String.Format("{0:MM/dd/yyyy}", collection["Ngaygiao"]);
            ddh.Ngaygiao = DateTime.Parse(ngaygiao);
            var ghichu = collection["Ghichu"];
            ddh.Ghichu = ghichu;
            ddh.Tinhtranggiaohang = false;
            ddh.Dathanhtoan = false;
            data.DONDATHANGs.InsertOnSubmit(ddh);
            data.SubmitChanges();
            //Them chi tiet don hang            
            foreach (var item in gh)
            {
                CHITIETDONTHANG ctdh = new CHITIETDONTHANG();
                ctdh.MaDonHang = ddh.MaDonHang;
                ctdh.MaSP = item.iMaSp;
                ctdh.Soluong = item.iSoluong;
                ctdh.Dongia = (decimal)item.dDongia;
                data.CHITIETDONTHANGs.InsertOnSubmit(ctdh);
            }
            data.SubmitChanges();
            Session["Giohang"] = null;
            return RedirectToAction("Xacnhandonhang", "Giohang");
        }
        public ActionResult Xacnhandonhang()
        {
            return View();
        }
    }
}

shopban/Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using shopban.Models;

namespace shopban.Controllers
{
    public class SanphamController : Controller
    {
        ShopDataDataContext data = new ShopDataDataContext();
        // GET: Sanpham
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult TenNhaCungCap(int id)
        {
            var sp = from s in data.SANPHAMs where s.MaNCC == id select s;
            return View(sp);
        }
        public ActionResult SPLoai(int id)
        {
            var sp = from s in data.SANPHAMs where s.MaL == id select s;
            return View(sp);
        }
        public ActionResult chitietsanpham(int id)
        {
            var sp = from s in data.SANPHAMs where s.MaSP == id select s;
            return View(sp);
        }
        public ActionResult SPDanhMuc(int id)
        {
            var sp = from s in data.SANPHAMs
                     join l in data.LOAIs
                     on s.MaL equals l.MaL
                     where l.MaDM == id
                     select new SanPham_Loai {
                         MaSp = s.MaSP,
                         MaL = l.MaL,
                         TenSp = s.TenSP,
                         Anhbia = s.Anhbia,
                         Mota = s.Mota,
                         Gia = s.Giaban,
                     };
            return View(sp);
        }
       
    }
}

shopban/Views/Giohang/DatHang.cshtml
@using shopban.Models
@model List<Giohang>
@{
    ViewBag.Title = "DatHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="checkout-area pb-100px">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="billing-info-wrap">
                    <h3>Billing Details</h3>
                    <div class="row">
                        <table>
                            @using (Html.BeginForm())
                            {
                                @Html.ValidationSummary(true)
                                <div class="col-lg-12">
                                    <div class="billing-info mb-20px">
                                        <label>Tên Khách Hàng</label>
                                        <input type="text" placeholder=" @kh.HoTen" />
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="billing-info mb-20px">
                                        <label>Địa chỉ</label>
                                        <input type="text" placeholder="@kh.DiachiKH" />
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="billing-info mb-20px">
                                        <label>Phone</label>
                                        <input type="text" placeholder="@kh.DienthoaiKH" />
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="billing-info mb-20px">
                                        <label>Email Address</label>
                                        <input type="text" placeholder="@kh.Email" />
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="billing-info mb-20px">
                                        <label>Ngày đặt</label>
                                        <input type="text" placeholder="@DateTime.Now.ToShortDateString()" />
                                    </div>
                                </div>
                                <div class="col-lg-6 col-md-6">
                                    <div class="billing-info mb-20px">
                                        <label>Ngày đặt</label>
                                        <input type="date" name="Ngaygiao" />
                                    </div>
                                </div>

                                <div class="additional-info-wrap">
                                    <div class="additional-info">
                                        <label>Ghi chú</label>
                                        <textarea placeholder="Notes about your order, e.g. special notes for delivery. " name="Ghichu"></textarea>
                                    </div>
                                </div>
                                <div>
                                    <input style="border:solid #000; padding:15px;" type="Submit" value="ĐỒNG Ý ĐẶT HÀNG" />
                                </div>
                            }
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-5 mt-md-30px mt-lm-30px ">
                <div class="your-order-area">
                    <h3>Your order</h3>
                    <div class="your-order-wrap gray-bg-4">
                        <div class="your-order-product-info">
                            <div class="your-order-top">
                                <ul>
                                    <li>Product</li>
                                    <li>Total</li>
                                </ul>
                            </div>
                            <div class="your-order-middle">
                                @foreach (var item in Model)
                                {
                                    using (Html.BeginForm("CapnhatGiohang", "Giohang", new { @iMaSp = item.iMaSp }))
                                    {
                                        <ul>
                                            <li><span class="order-middle-left">@item.sTenSp X @item.iSoluong</span> <span class="order-price">@String.Format("{0:0,0}", item.dDongia) </span></li>
                                            
                                        </ul>
                                       
                                    }
                                 
                                }
                            </div>
                            <div class="your-order-bottom">
                                <ul>
                                    <li class="your-order-shipping">Shipping</li>
                                    <li>Free shipping</li>
                                </ul>
                            </div>
                            <div class="your-order-total">
                                <ul>
                                    <li class="order-total">TỔNG TIỀN</li>
                                    <li>@String.Format("{0:0,0}", ViewBag.Tongtien)</li>
                                </ul>
                            </div>
                        </div>
                        <div class="payment-method">
                            <div class="payment-accordion element-mrg">
                                <div class="panel-group" id="accordion">
                                    
                                    <div class="panel payment-accordion">
                                        <div class="panel-heading" id="method-two">
                                            <h4 class="panel-title">
                                                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#method2">
                                                    Thanh toán qua thẻ ngân hàng
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="method2" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Cung cấp thông tin ngân hàng</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel payment-accordion">
                                        <div class="panel-heading" id="method-three">
                                            <h4 class="panel-title">
                                                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#method3">
                                                    Thanh Toán COD
                                                </a>
                                            </h4>
                                        </div>
                                        <div id="method3" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

shopban/Views/Giohang/Gia.cshtml
<div class="header-tools d-flex">
    <div class="cart-info d-flex align-self-center">
        <a title="cart" href="#offcanvas-cart" class="bag offcanvas-toggle"><i class="las la-baby-carriage"></i><span class="item-total">@String.Format("{0:0,0}", ViewBag.Tongtien)</span><span class="item-count">@ViewBag.Tongsoluong item(s)</span></a>
    </div>
</div>

shopban/Views/Giohang/GioHang.cshtml
@using shopban.Models
@model List<Giohang>
@{
    ViewBag.Title = "GioHang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="margin-top: 100px;" class="cart-main-area pb-100px">
    <div class="container">
        <h3 class="cart-page-title">Giỏ Hàng</h3>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="table-content table-responsive cart-table-content">
                        <table>
                            <thead>
                                <tr>
                                    <th>Ảnh</th>
                                    <th>Tên sản phẩm</th>
                                    <th>Giá</th>
                                    <th>Số lượng</th>
                                    <th>Thành Tiền</th>
                                    <th>Xóa</th>
                                    <th>Cập nhập</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr style="text-align:center; font-weight:bold">
                                        <td><img style="width:250px;height:250px;" src="@item.sAnhbia"></td>
                                        <td class="product-name"> @item.sTenSp</td>

                                        @using (Html.BeginForm("CapnhatGiohang", "Giohang", new { @iMaSp = item.iMaSp }))
                                        {
                                            <td class="product-price-cart">@String.Format("{0:0,0}", item.dDongia) </td>

                                            <td class="product-quantity">
                                                <div class="cart-plus-minus">
                                                    <input class="cart-plus-minus-box" type="text" name="txtSoluong" value="@item.iSoluong" />
                                                </div>
                                            </td>
                                            <td>@String.Format("{0:0,0}", item.dThanhtien) </td>

                                            <td class="product-price-cart"> @Html.ActionLink("Xóa", "XoaGiohang", new { @iMaSp = item.iMaSp })</td>
                                            <td> <input type="submit" value="Cập Nhật" /></td>
                                        }
                                    </tr>
                                }
                                <tr style="font-weight: bold; text-align:right; color:red">
                                    <td colspan="4"> Số lượng: @ViewBag.Tongsoluong </td>
                                    <td colspan="5"> Tổng tiền: @String.Format("{0:0,0}", ViewBag.Tongtien) VNĐ </td>
                                </tr>
                                <tr style="font-weight: bold; color:blue; text-align:right ">
                                    <td colspan="9">
                                        @Html.ActionLink("Xóa Giỏ Hàng", "XoaTatcaGiohang")
                                    </td>
                                </tr>
                                <tr style="font-weight: bold; color:blue; text-align:right ">
                                    <td colspan="9" align="center">
                                        @Html.ActionLink("ĐẶT HÀNG", "Dathang", "GioHang")
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
            </div>
        </div>
    </div>
</div>

shopban/Views/Giohang/Index.cshtml
@using shopban.Models
@model List<Giohang>
<div id="offcanvas-cart" class="offcanvas offcanvas-cart">
    <div class="inner">
        <div class="head">
            <span class="title">Cart</span>
            <button class="offcanvas-close">×</button>
        </div>
        <div class="body customScroll">
            <ul class="minicart-product-list">
                @foreach (var item in Model)
                {
                    <li>
                        <a href="@Url.Action("chitietsanpham","Sanpham",new {id = @item.iMaSp })" class="image"><img src="@item.sAnhbia" alt="Cart product Image"></a>
                        <div class="content">
                            <a href="@Url.Action("chitietsanpham","Sanpham",new {id = @item.iMaSp })" class="title">@item.sTenSp</a>
                            <span class="quantity-price">@item.iSoluong X <span class="amount">@String.Format("{0:0,0}", @item.dDongia)</span></span>
                            <a href="#" class="remove">×</a>
                        </div>
                    </li>
                }
            </ul>          
        </div>
        <div class="foot">
            <div class="sub-total">
                <table class="table">
                    <tbody>
                        
                        <tr>
                            <td class="text-left">Tổng cộng :</td>
                            <td class="text-right theme-color">@String.Format("{0:0,0}", ViewBag.Tongtien)</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="buttons">
                <a href="@Url.Action("GioHang","Giohang")" class="btn btn-dark btn-hover-primary mb-30px">Giỏ Hàng</a>
                <a href="@Url.Action("DatHang","Giohang")" class="btn btn-outline-dark current-btn">Thanh Toán</a>
            </div>
            <p class="minicart-message">Miễn phí đơn hàng với hóa đơn trên 200</p>
        </div>
    </div>
</div>

shopban/Views/Giohang/Xacnhandonhang.cshtml
@{
    ViewBag.Title = "Xacnhandonhang";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Đơn hàng của quý khách đã được chúng tôi ghi nhận. Chúng tôi sẽ liên hệ quý khách trong thời gian sớm nhất và giao hàng đúng hẹn</h2>
<p style="text-align:center">
    @Html.ActionLink("VỀ TRANG CHỦ", "Index", "Home")
</p>